### ISSUE TITLE
Importing References from JSONbin error

### ISSUE THREAD

**Issue by mifilip** [theemo-tokens/theemo#659]
When using `Import` under `Tools`, I can't seem to be able to import references.

Here's the error from the Figma Console 

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/64547167/215726456-eadc47a5-b0c7-4f7c-ba09-f219744e2ef8.png">

**Comment by gossi** [comment]
This is part of the [`figma-theemo`](https://github.com/theemo-tokens/figma-theemo) plugin, which had a release this summer, touched the entire code, including the import feature.

Please try the new version of the plugin. If the problem persists, please re-open an issue over at the other repo.

Thank you :)
